### ISSUE TITLE
Operation not permitted unless I'm root, even though /proc/sys/net/ipv4/ping_group_range is set

### ISSUE THREAD

**Issue by joatca** [robacarp/icmp.cr#2]
Nice library! Was worried I'd have to code ping myself. :-)

I can't get it to work on Linux unless I'm root, even though I think I have /proc/sys/net/ipv4/ping_group_range set correctly. Any idea what might be wrong?

```
$ cat /proc/sys/net/ipv4/ping_group_range 
0	2147483647
$ uname -r
4.15.3-2-ARCH
$ id
uid=1000(fraser) gid=1000(fraser) groups=1000(fraser),10(wheel),14(uucp),100(users),614(adbusers)
$ crystal run test.cr 
failed to create socket:: Operation not permitted (Errno)
  from /usr/lib/crystal/socket.cr:0:5 in 'initialize'
  from /usr/lib/crystal/socket.cr:69:3 in 'initialize'
  from IPSocket
  from lib/icmp/src/icmp.cr:44:9 in 'initialize'
  from lib/icmp/src/icmp.cr:26:5 in 'new'
  from test.cr:16:14 in '__crystal_main'
  from /usr/lib/crystal/crystal/main.cr:11:3 in '_crystal_main'
  from /usr/lib/crystal/crystal/main.cr:112:5 in 'main_user_code'
  from /usr/lib/crystal/crystal/main.cr:101:7 in 'main'
  from /usr/lib/crystal/crystal/main.cr:135:3 in 'main'
  from __libc_start_main
  from _start
  from ???
$ sudo crystal run test.cr 
0 valid_response took 2ms
1 valid_response took 1ms
2 valid_response took 1ms
```

The code is just your example modified with a local IP address (although 8.8.8.8 obviously doesn't work either):

```ruby
require "icmp"

statistics = ICMP::Ping.new("192.168.0.5").ping(count: 3) do |request|
  puts "#{request.sequence} #{request.status} took #{request.roundtrip_time}ms"
end
p statistics
```

**Comment by robacarp** [comment]
@joatca I'm sorry, that's irritating. Unfortunately my ignorance about selinux and other permission systems is likely the issue.

I spent a bunch of time trying to figure out the right way to do this and it runs on my linux cloud server without issue, but I am totally new to selinux and friends with this endeavor. Now that I think about it, it's running in docker, so the process is probably root anyway, and I had to spend an afternoon looking up docker commands to bless the container.

[This line is almost certainly the culprit](https://github.com/robacarp/icmp.cr/blob/e75950f32daf9148a1a6505157b974dd01ae4fe6/src/icmp.cr#L34), and it may help to try it out as a DGRAM instead of a raw socket.


What linux are you running on?

Edit:

It's been a few months, but I think it's also possible to bless the executable with the specific permission to open a raw socket. I gather this is how a system `ping` utility does it.

**Comment by joatca** [comment]
Thanks for the response.

I'm on Arch Linux.

I've noticed a couple of curious things:

1. selinux isn't enabled (or supported) in standard Arch, so that's not the problem.
2. /usr/bin/ping is *not* setuid root, yet it works as a regular user. However it fails if I "strace" it. If I set ping_group_range, it works again, so at least that is being honoured. That makes me a bit confused about exactly what permissions are required here. I suspect ping is trying an ICMP socket then falling back to a plain raw socket if that fails - but the ping_group_range only applies to ICMP sockets, so...

I'll do some more digging and see if I can figure out what's going on. If I get anywhere I'll submit a pull request to update the README.

**Comment by duraki** [comment]
I can confirm that this is issue (reproducible here too) and it's probably up to raw socket just as @robacarp noted out. This does not seems like a lib issue.

As far as I know, creating raw socket requires higher privileges. This is not up to selinux enforcement but rather, in Linux, raw socket has eligible rights to read all network packets - which is major security issue if not allowed manually.

I managed to walkaround the issue by setting correct SUID for binary files (`chmod +s`). Check manpages for `setcap` for another possible solution (`setcap cap_net_raw`). This way you are not required to have `sudo`.

**Comment by robacarp** [comment]
@duraki yes, thank you for the reminder, I had forgotten I spent a fair amount of time with setcap as well.

**Comment by joatca** [comment]
@duraki is absolutely correct, it's a Linux restriction unrelated to this shard. (Thanks!) The magic needed to make it work as a non-root process (with this shard or with anything else) is:

    setcap cap_net_raw=ep executable-name

"e" is "effective" and "p" is "permitted". I've read capabilities(7) for the descriptions of "effective" and "permitted" but I'm still unclear on why both are needed. Certainly having just one or the other (=p or =e) doesn't work.
