### ISSUE TITLE
Arithmetic overflow

### ISSUE THREAD

**Issue by packetq** [robacarp/icmp.cr#7]
Hi,

I get the following when I try to run the example in the readme. I'm using crystal 0.32.1 on Ubuntu Server 16.04 LTS.

Unhandled exception: Arithmetic overflow (OverflowError)
  from lib/icmp/src/icmp/packet.cr:0:16 in 'calculate_checksum'
  from lib/icmp/src/icmp/request.cr:29:19 in 'initialize'
  from lib/icmp/src/icmp/request.cr:14:5 in 'new'
  from lib/icmp/src/icmp.cr:54:9 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:97:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:86:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???

Thanks,
-G

**Comment by robacarp** [comment]
Thanks @packetq
